#!/usr/bin/env bash
# script that display information about subdomains

display_Info () {
    result=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $result" |  awk '{print "The subdomain " $1 " is a " $(NF-1) " record and points to " $NF}'
}

if [ "$#" == 1 ]
then
  display_Info "$1" "www"
  display_Info "$1" "lb-01"
  display_Info "$1" "web-01"
  display_Info "$1" "web-02"
elif [ "$#" == 2 ]
then
  display_Info "$1" "$2"
fi
