#!/usr/bin/env bash
#script that configure Nginx to redirect to a page /redirect_me

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' >  /var/www/html/index.html
config="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	}"
bash -c "echo -e '$config' > /etc/nginx/sites-enabled/default"
service nginx start
