#!/usr/bin/env bash
#script that install nginx on my web-01, web-02 and load balncer

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
config="server {
	add_header X-Served-By \$hostname;
	}"
bash -c "echo -e '$config' > /etc/nginx/sites-enabled/default"
service nginx start
