#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /usr/share/nginx/html;
        index index.html index.htm;
        server_name localhost;
        location / {
                try_files \$uri \$uri/ =404;
        }" > /etc/nginx/sites-enabled/default
service nginx start
