#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

pids=$(pgrep -f bash)

for pid in $pids; do
	echo "$pid $(cat /proc/"$pid"/comm)"
done
