#!/usr/bin/env bash
#script that displays from the content of the file /etc/passwd.
#username
#user id
#Home directory path for the user

file="/etc/passwd"
while read -r line; do
	username=$(echo "$line" | cut -d ':' -f1)
	uid=$(echo "$line" | cut -d ':' -f3)
	home=$(echo "$line" | cut -d ':' -f6)
	echo "$username:$uid:$home"
done < "$file"
