#!/usr/bin/env bash
#script that displays from the content of the file /etc/passwd
#+using the while loop + IFS.

file="/etc/passwd"
while IFS=: read -r line; do
	USERNAME=$(echo "$line" | cut -d ':' -f1)
	PASSWORD=$(echo "$line" | cut -d ':' -f2)
	uid=$(echo "$line" | cut -d ':' -f3)
	GROUP_ID=$(echo "$line" | cut -d ':' -f4)
	USER_ID_INFO=$(echo "$line" | cut -d ':' -f5)
	home=$(echo "$line" | cut -d ':' -f6)
	COMMAND=$(echo "$line" | cut -d ':' -f7)
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $home and rides $COMMAND. $uid's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$file"
